/**
 * ZIP Exporter - 시퀀스 프레임을 ZIP으로 패키징
 * JSZip을 사용하여 프레임 PNG + metadata.json 생성
 */
import JSZip from 'jszip';

/**
 * 프레임 배열을 ZIP으로 패키징하고 다운로드
 * @param {Array<{index: number, blob: Blob, duration: number, filename: string}>} frames - 렌더링된 프레임 배열
 * @param {Object} options - 옵션
 * @param {string} options.projectName - ZIP 파일명 (기본: 'talkstudio')
 * @param {Object} options.metadata - 추가 메타데이터
 * @returns {Promise<Blob>} 생성된 ZIP Blob
 */
export async function createSequenceZip(frames, options = {}) {
  const {
    metadata = {},
  } = options;

  if (!frames || frames.length === 0) {
    throw new Error('No frames to export');
  }

  const zip = new JSZip();

  // 1. 프레임 이미지 폴더 생성 및 추가
  const framesFolder = zip.folder('frames');
  for (const frame of frames) {
    framesFolder.file(frame.filename, frame.blob);
  }

  // 2. 메타데이터 생성
  const totalDuration = frames.reduce((sum, f) => sum + f.duration, 0);
  const sequenceMetadata = {
    version: '1.0',
    generator: 'TalkStudio',
    createdAt: new Date().toISOString(),
    totalFrames: frames.length,
    totalDuration: Math.round(totalDuration * 100) / 100, // 소수점 2자리
    fps: 30, // 권장 FPS
    resolution: metadata.resolution || '390x844',
    frames: frames.map((f) => ({
      index: f.index,
      filename: `frames/${f.filename}`,
      duration: f.duration,
      messagePreview: f.messageText || '',
    })),
    ...metadata,
  };

  // 3. 메타데이터 JSON 추가
  zip.file('metadata.json', JSON.stringify(sequenceMetadata, null, 2));

  // 4. README 추가 (사용법 안내)
  const readme = `# TalkStudio Sequence Export

## Contents
- frames/: PNG 이미지 시퀀스
- metadata.json: 프레임별 duration 정보

## Usage
이 ZIP을 백엔드 서버에 업로드하거나
ffmpeg를 사용하여 직접 영상으로 변환할 수 있습니다.

## FFmpeg Example
\`\`\`bash
# 프레임을 영상으로 변환 (duration 무시, 고정 FPS)
ffmpeg -framerate 1 -i frames/frame_%04d.png -c:v libx264 -pix_fmt yuv420p output.mp4

# metadata.json의 duration을 사용하려면 별도 스크립트 필요
\`\`\`

Generated by TalkStudio
`;
  zip.file('README.md', readme);

  // 5. ZIP 생성
  const content = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });

  return content;
}

/**
 * ZIP Blob을 다운로드
 * @param {Blob} blob - ZIP Blob
 * @param {string} filename - 다운로드 파일명
 */
export function downloadZip(blob, filename = 'talkstudio_sequence.zip') {
  const url = URL.createObjectURL(blob);

  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();

  // 정리
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * 프레임을 ZIP으로 패키징하고 즉시 다운로드 (편의 함수)
 * @param {Array} frames - 렌더링된 프레임 배열
 * @param {Object} options - 옵션
 */
export async function exportAndDownload(frames, options = {}) {
  const { projectName = 'talkstudio' } = options;

  const blob = await createSequenceZip(frames, options);
  const timestamp = new Date().toISOString().slice(0, 10).replace(/-/g, '');
  const filename = `${projectName}_sequence_${timestamp}.zip`;

  downloadZip(blob, filename);

  return { blob, filename };
}

export default createSequenceZip;
