# ai_agent_system/src/models/generated_content_model.py
from datetime import datetime
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field, BeforeValidator, ConfigDict
from typing_extensions import Annotated
from bson import ObjectId

PyObjectId = Annotated[str, BeforeValidator(str)]

class GeneratedContent(BaseModel):
    """
    Represents content generated by the Upstage API.
    """
    id: Optional[PyObjectId] = Field(alias="_id", default=None) # Internal ID
    relatedDiscordMessageIds: List[str] = Field(default_factory=list, description="IDs of Discord messages used for generation")
    contentType: str = Field(..., description="Type of content generated (e.g., 'summary', 'faq_answer', 'idea_list')")
    generatedText: str = Field(..., description="The main text generated by Upstage API")
    upstageModelUsed: str = Field(..., description="Name of the Upstage model used for generation")
    promptUsed: str = Field(..., description="The prompt sent to the Upstage API")
    temperature: float = Field(..., description="Temperature parameter used during generation")
    generatedAt: datetime = Field(default_factory=datetime.utcnow, description="Timestamp when the content was generated")
    feedback: Optional[Dict[str, Any]] = Field(default=None, description="User feedback on the generated content")

    model_config = ConfigDict(
        populate_by_name=True,
        arbitrary_types_allowed=True,
        json_encoders={ObjectId: str},
        json_schema_extra={
            "example": {
                "relatedDiscordMessageIds": ["msg1_id", "msg2_id"],
                "contentType": "summary",
                "generatedText": "This is a summary of the conversation...",
                "upstageModelUsed": "llama-2-70b-chat",
                "promptUsed": "Summarize the following...",
                "temperature": 0.7,
                "generatedAt": "2023-11-20T11:00:00Z"
            }
        }
    )
